# ---------------------------------------------------------
# *_: Model Objects
# ---------------------------------------------------------
type Comment {
  id:               ID!
  comment:          String!
  postId:           ID!
  authorId:         ID!

  createdAt:        String!
  updatedAt:        String
}

# ---------------------------------------------------------
# *_: Input Objects
# ---------------------------------------------------------
input CreateCommentInput {
  comment:          String!
  postId:           ID!
}

input UpdateCommentInput {
  id:               ID!
  comment:          String!
}

input DeleteCommentInput {
  id:               ID!
}

# ---------------------------------------------------------
# *_: Return Payloads
# ---------------------------------------------------------
type CommentPayload {
  id:               ID
  comment:          String
  postId:           ID
  post:             PostPayload
  authorId:         ID
  author:           UserPayload

  createdAt:        String
  updatedAt:        String
}

type CommentsPayload {
  count:            Int
  comments:        [CommentPayload]
}

# ---------------------------------------------------------
# *_: Queries
# ---------------------------------------------------------
type Query {
  # TODO: Get comments made by authUser
  getMyComments(skip: Int, limit: Int):              [CommentPayload]

  # DONE: Get Post's comment
  getComments(postId: ID!, skip: Int, limit: Int):    CommentsPayload
}

# ---------------------------------------------------------
# *_: Mutations
# ---------------------------------------------------------
type Mutation {
  # DONE: Create a post comment
  createComment(input: CreateCommentInput!):          CommentPayload

  # DONE: Update a post comment
  updateComment(input: UpdateCommentInput!):          Boolean

  # DONE: Delete a post comment
  deleteComment(input: DeleteCommentInput!):          Boolean
}

# ---------------------------------------------------------
# *_: Subscriptions
# ---------------------------------------------------------
