# ---------------------------------------------------------
# *_: Model Objects
# ---------------------------------------------------------

type Comment {
  id:               ID!
  comment:          String
  image:            String
  imagePublicId:    String
  stickerId:        ID
  postId:           ID!
  authorId:         ID!

  createdAt:        String!
  updatedAt:        String!
}

# ---------------------------------------------------------
# *_: Input Objects
# ---------------------------------------------------------

input CreateCommentInput {
  comment:          String
  image:            Upload
  stickerId:        ID
  postId:           ID!
}

input UpdateCommentInput {
  id:               ID!
  comment:          String
  image:            Upload
  stickerId:        ID
  deleteImage:      Boolean
  deleteSticker:    Boolean
}

input DeleteCommentInput {
  id:               ID!
}

# ---------------------------------------------------------
# *_: Return Payloads
# ---------------------------------------------------------

type CommentPayload {
  id:               ID
  comment:          String
  image:            String
  imagePublicId:    String
  stickerId:        ID
  postId:           ID
  authorId:         ID

  sticker:          StickerPayload
  post:             PostPayload
  author:           UserPayload

  createdAt:        String
  updatedAt:        String
}

type CommentsPayload {
  count:            Int
  comments:        [CommentPayload]
}

# ---------------------------------------------------------
# *_: Queries
# ---------------------------------------------------------

type Query {
  getComments(postId: ID!, skip: Int, limit: Int):    CommentsPayload
}

# ---------------------------------------------------------
# *_: Mutations
# ---------------------------------------------------------

type Mutation {
  createComment(input: CreateCommentInput!):          CommentPayload

  updateComment(input: UpdateCommentInput!):          Boolean

  deleteComment(input: DeleteCommentInput!):          Boolean
}

# ---------------------------------------------------------
# *_: Subscriptions
# ---------------------------------------------------------
