# ---------------------------------------------------------
# * Model Objects
# ---------------------------------------------------------

type FollowID {
  userId:         ID!
  followerId:     ID!
}

type Follow {
  _id:            FollowID!

  createdAt:      String!
  updatedAt:      String!
}


# ---------------------------------------------------------
# * Input Objects
# ---------------------------------------------------------

input GetFollowingOrFollowerInput {
  username: String!
  idOnly: Boolean
  skip: Int
  limit: Int
}

input CreateOrDeleteFollowInput {
  userId:         ID!
}

# ---------------------------------------------------------
# * Response Payloads
# ---------------------------------------------------------

type FollowerOrFollowingPayload {
  count:          Int
  users:         [UserPayload]
}

# ---------------------------------------------------------
# * Queries
# ---------------------------------------------------------

type Query {
  getFollowings(input: GetFollowingOrFollowerInput!):     FollowerOrFollowingPayload @auth(optional: true)

  getFollowers(input: GetFollowingOrFollowerInput!):      FollowerOrFollowingPayload @auth(optional: true)
}

# ---------------------------------------------------------
# * Mutations
# ---------------------------------------------------------
type Mutation {
  createFollow(input: CreateOrDeleteFollowInput!):        Boolean @auth

  deleteFollow(input: CreateOrDeleteFollowInput!):        Boolean @auth
}

# ---------------------------------------------------------
# * Subscriptions
# ---------------------------------------------------------
