# ---------------------------------------------------------
# *_: Model Objects
# ---------------------------------------------------------
type Follow {
  _id:            FollowID!

  createdAt:      String!
  updatedAt:      String
}

type FollowID {
  userId:         ID!
  followerId:     ID!
}

# ---------------------------------------------------------
# *_: Input Objects
# ---------------------------------------------------------
input CreateOrDeleteFollowInput {
  userId:         ID!
}

# ---------------------------------------------------------
# *_: Return Payloads
# ---------------------------------------------------------
type FollowerOrFollowingPayload {
  count:          Int
  users:         [UserPayload]
}

# ---------------------------------------------------------
# *_: Queries
# ---------------------------------------------------------
type Query {
  # DONE: Get follows made by user
  getUserFollowings(username: String!, skip: Int, limit: Int):       FollowerOrFollowingPayload

  # DONE: Get user's followers
  getUserFollowers(username: String!, skip: Int, limit: Int):        FollowerOrFollowingPayload
}

# ---------------------------------------------------------
# *_: Mutations
# ---------------------------------------------------------
type Mutation {
  # DONE: Create a following/follower relationship between users
  createFollow(input: CreateOrDeleteFollowInput!):      Boolean

  # DONE: Delete a following/follower relationship between users
  deleteFollow(input: CreateOrDeleteFollowInput!):      Boolean
}

# ---------------------------------------------------------
# *_: Subscriptions
# ---------------------------------------------------------
