# ---------------------------------------------------------
# Model Objects
# ---------------------------------------------------------

# ---------------------------------------------------------
# Input Objects
# ---------------------------------------------------------
input CreateFollowInput {
  userId:         ID!
}

input DeleteFollowInput {
  userId:         ID!
}

# ---------------------------------------------------------
# Return Payloads
# ---------------------------------------------------------

# ---------------------------------------------------------
# Queries
# ---------------------------------------------------------
type Query {
  # Gets follows made by authUser
  getMyFollowings(skip: Int, limit: Int):       [UserPayload]

  # Gets authUser's followers
  getMyFollowers(skip: Int, limit: Int):        [UserPayload]
}

# ---------------------------------------------------------
# Mutations
# ---------------------------------------------------------
type Mutation {
  # Creates a following/follower relationship between users
  createFollow(input: CreateFollowInput!):     [String]

  # Deletes a following/follower relationship between users
  deleteFollow(input: DeleteFollowInput!):      Boolean
}

# ---------------------------------------------------------
# Subscriptions
# ---------------------------------------------------------
