# ---------------------------------------------------------
# Model Objects
# ---------------------------------------------------------

# ---------------------------------------------------------
# Input Objects
# ---------------------------------------------------------
input CreateLikeInput {
  postId:       ID!
}

input DeleteLikeInput {
  postId:       ID!
}

# ---------------------------------------------------------
# Return Payloads
# ---------------------------------------------------------

# ---------------------------------------------------------
# Queries
# ---------------------------------------------------------
type Query {
  # Gets likes made by authUser
  getMyLikes(skip: Int, limit: Int):         [PostPayload]
}

# ---------------------------------------------------------
# Mutations
# ---------------------------------------------------------
type Mutation {
  # Creates a like for post
  createLike(input: CreateLikeInput!):       [String]

  # Deletes a post like
  deleteLike(input: DeleteLikeInput!):        Boolean
}

# ---------------------------------------------------------
# Subscriptions
# ---------------------------------------------------------
