# ---------------------------------------------------------
# *_: Model Objects
# ---------------------------------------------------------
type Like {
  _id:          LikeId!

  createdAt:    String!
  updatedAt:    String
}

type LikeId {
  postId:       ID!
  userId:       ID!
}

# ---------------------------------------------------------
# *_: Input Objects
# ---------------------------------------------------------
input CreateOrDeleteLikeInput {
  postId:       ID!
}

# ---------------------------------------------------------
# *_: Return Payloads
# ---------------------------------------------------------
type LikePayload {
  post:         PostPayload
  user:         UserPayload

  createdAt:    String
  updatedAt:    String
}

type LikesPayload {
  count:        Int
  likes:       [LikePayload]
}

# ---------------------------------------------------------
# *_: Queries
# ---------------------------------------------------------
type Query {
  # TODO: Get likes made by authUser
  getMyLikes(skip: Int, limit: Int):          LikesPayload

  # DONE: Get post's likes
  getLikes(postId: ID!):                      LikesPayload
}

# ---------------------------------------------------------
# *_: Mutations
# ---------------------------------------------------------
type Mutation {
  # DONE: Create a like for post
  createLike(input: CreateOrDeleteLikeInput!):        Boolean

  # DONE: Delete a post like
  deleteLike(input: CreateOrDeleteLikeInput!):        Boolean
}

# ---------------------------------------------------------
# *_: Subscriptions
# ---------------------------------------------------------
