# ---------------------------------------------------------
# *_: Model Objects
# ---------------------------------------------------------

type Message {
  id:               ID!
  senderId:         ID!
  recipientId:      ID!
  message:          String
  image:            String
  imagePublicId:    String
  stickerId:        String
  seen:            [String]

  createdAt:        String
  updatedAt:        String
}

# ---------------------------------------------------------
# *_: Input Objects
# ---------------------------------------------------------

input CreateMessageInput {
  recipientId:      ID!
  message:          String
  image:            Upload
  stickerId:        ID
}

input UpdateMessageSeenInput {
  withUserId:       ID!
}

# ---------------------------------------------------------
# *_: Return Payloads
# ---------------------------------------------------------

type MessagePayload {
  id:               ID
  senderId:         ID
  sender:           UserPayload
  recipientId:      ID
  recipient:        UserPayload
  message:          String
  image:            String
  imagePublicId:    String
  stickerId:        String
  sticker:          StickerPayload
  seen:            [UserPayload]

  createdAt:        String
  updatedAt:        String
}

type ConversationsPayload {
  id:               ID
  username:         String
  fullName:         String
  image:            String
  isOnline:         Boolean

  lastMessage:      MessagePayload
  unseenCount:      Int
}

# ---------------------------------------------------------
# *_: Queries
# ---------------------------------------------------------

type Query {
  # Gets authUser's messages
  getMessages(withUserId: ID!):                [MessagePayload]

  # Gets authUser's conversations
  getConversations:                            [ConversationsPayload]
}

# ---------------------------------------------------------
# *_: Mutations
# ---------------------------------------------------------

type Mutation {
  # Creates a message
  createMessage(input: CreateMessageInput!):            MessagePayload

  # Updates message seen values for user
  updateMessageSeen(input: UpdateMessageSeenInput!):    Boolean
}

# ---------------------------------------------------------
# *_: Subscriptions
# ---------------------------------------------------------

type Subscription {
  # Subscribes to message created event
  messageCreated(withUserId: ID!):              MessagePayload

  # Subscribes to new conversation event
  newConversation:                              ConversationsPayload
}
