# ---------------------------------------------------------
# Model Objects
# ---------------------------------------------------------
enum NotificationType {
  LIKE
  FOLLOW
  COMMENT
}

enum NotificationOperationType {
  CREATE
  DELETE
}

type Notification {
  id:                 ID!
  type:               NotificationType
  relativeData:       String
  authorId:           ID!
  seen:               Boolean

  createdAt:          String
}

# ---------------------------------------------------------
# Input Objects
# ---------------------------------------------------------

input DeleteNotificationInput {
  id:                 ID!
}

# ---------------------------------------------------------
# Return Payloads
# ---------------------------------------------------------
type NotificationPayload {
  id:                 ID
  type:               NotificationType
  relativeData:       String
  authorId:           ID
  author:             UserPayload

  createdAt:          String
}

type NotificationsPayload {
  count:              Int!
  notifications:     [NotificationPayload]!
}

type NotificationCreatedOrDeletedPayload {
  operation:          NotificationOperationType!
  notification:       NotificationPayload
}

# ---------------------------------------------------------
# Queries
# ---------------------------------------------------------
type Query {
  # Gets notifications for authUser
  getMyNotifications(skip: Int, limit: Int):            NotificationsPayload
}

# ---------------------------------------------------------
# Mutations
# ---------------------------------------------------------
type Mutation {
  # Updates notification seen values for user
  updateNotificationSeen:                                 Boolean

  # Deletes a notification
  deleteNotification(input: DeleteNotificationInput!):    Boolean
}

# ---------------------------------------------------------
# Subscriptions
# ---------------------------------------------------------
type Subscription {
  # Subscribes to notification created or deleted event
  notificationCreatedOrDeleted:                           NotificationCreatedOrDeletedPayload
}
