# ---------------------------------------------------------
# *_: Model Objects
# ---------------------------------------------------------
type Notification {
  id:                 ID!
  type:               NotificationType!
  additionalData:     String
  fromId:             ID!
  toId:               ID!
  seen:               Boolean!

  createdAt:          String!
  updatedAt:          String
}

enum NotificationType {
  LIKE
  COMMENT
  FOLLOW
}

enum NotificationOperationType {
  CREATE
  DELETE
}

# ---------------------------------------------------------
# *_: Input Objects
# ---------------------------------------------------------

input DeleteNotificationInput {
  id:                 ID!
}

# ---------------------------------------------------------
# *_: Return Payloads
# ---------------------------------------------------------
type NotificationPayload {
  id:                 ID
  type:               String
  additionalData:     String
  fromId:             ID
  from:               UserPayload
  toId:               ID

  createdAt:          String
  updatedAt:          String
}

type NotificationsPayload {
  count:              Int
  unseen:             Int
  notifications:     [NotificationPayload]
}

type NotificationCreatedOrDeletedPayload {
  operation:          NotificationOperationType!
  notification:       NotificationPayload
}

# ---------------------------------------------------------
# *_: Queries
# ---------------------------------------------------------
type Query {
  # DONE: Gets notifications for authUser
  getMyNotifications(skip: Int, limit: Int):              NotificationsPayload
}

# ---------------------------------------------------------
# *_: Mutations
# ---------------------------------------------------------
type Mutation {
  # DONE: Updates notification seen values for user
  updateNotificationSeen:                                 Boolean

  # DONE: Deletes a notification
  deleteNotification(input: DeleteNotificationInput!):    Boolean
}

# ---------------------------------------------------------
# *_: Subscriptions
# ---------------------------------------------------------
type Subscription {
  # DONE: Subscribes to notification created or deleted event
  notificationCreatedOrDeleted:                           NotificationCreatedOrDeletedPayload
}
