# ---------------------------------------------------------
# *_: Model Objects
# ---------------------------------------------------------

type Notification {
  id:                 ID!
  type:               NotificationType!
  postId:             ID
  commentId:          ID
  fromIds:           [ID]
  toId:               ID!
  seen:               Boolean!

  createdAt:          String!
  updatedAt:          String
}

enum NotificationType {
  LIKE
  COMMENT
  FOLLOW
  NOTIFICATION
}

# ---------------------------------------------------------
# *_: Input Objects
# ---------------------------------------------------------

input UpdateNotificationSeenInput {
  id:                 ID
  seenAll:            Boolean
}

input DeleteNotificationInput {
  id:                 ID!
}

# ---------------------------------------------------------
# *_: Return Payloads
# ---------------------------------------------------------

enum NotificationOperationType {
  CREATE
  DELETE
}

type NotificationPayload {
  id:                 ID
  type:               NotificationType
  postId:             ID
  commentId:          ID
  fromIds:           [ID]
  toId:               ID

  post:               PostPayload
  comment:            CommentPayload
  from:              [UserPayload]

  createdAt:          String
  updatedAt:          String
}

type NotificationsPayload {
  count:              Int
  unseen:             Int
  notifications:     [NotificationPayload]
}

type NotificationUpdatedPayload {
  operation:          NotificationOperationType
  type:               NotificationType
  dataId:             ID
  from:               UserPayload
}

# ---------------------------------------------------------
# *_: Queries
# ---------------------------------------------------------

type Query {
  # DONE: Get authUser's notifications
  getNotifications(skip: Int, limit: Int):                              NotificationsPayload
}

# ---------------------------------------------------------
# *_: Mutations
# ---------------------------------------------------------

type Mutation {
  # DONE: Update notification seen
  updateNotificationSeen(input: UpdateNotificationSeenInput!):          Boolean

  # DONE: Delete a notification
  deleteNotification(input: DeleteNotificationInput!):                  Boolean
}

# ---------------------------------------------------------
# *_: Subscriptions
# ---------------------------------------------------------

type Subscription {
  # DONE: Subscribe to notification created or deleted event
  notificationUpdated:                                                  NotificationUpdatedPayload
}
