# ---------------------------------------------------------
# *_: Model Objects
# ---------------------------------------------------------
type Post {
  id:             ID!
  title:          String
  images:        [PostImage]
  authorId:       ID!
  isPrivate:      Boolean!

  createdAt:      String!
  updatedAt:      String
}

type PostImage {
  image:          String
  imagePublicId:  String
}

# ---------------------------------------------------------
# *_: Input Objects
# ---------------------------------------------------------
input CreatePostInput {
  title:          String
  images:        [Upload]
  isPrivate:      Boolean!
}

input UpdatePostInput {
  id:             ID!
  title:          String
  isPrivate:      Boolean
}

input DeletePostInput {
  id:             ID!
}

enum GetPostsType {
  USER
  FOLLOWED
  EXPLORE
}

# ---------------------------------------------------------
# *_: Return Payloads
# ---------------------------------------------------------
type PostPayload {
  id:             ID
  title:          String
  image:          String
  imagePublicId:  String
  authorId:       ID
  isPrivate:      Boolean

  author:         UserPayload
  likeCount:      Int
  likes:         [LikePayload]
  commentCount:   Int
  comments:      [CommentPayload]

  createdAt:      String
  updatedAt:      String
}

type PostsPayload {
  count:          Int!
  posts:         [PostPayload]!
}

# ---------------------------------------------------------
# *_: Queries
# ---------------------------------------------------------
type Query {
  # DONE: Get posts by input operation
  getPosts(type: GetPostsType!, username: String, skip: Int, limit: Int):       PostsPayload

  # DONE: Get post by id
  getPost(postId: ID!):                                                         PostPayload

}

# ---------------------------------------------------------
# *_: Mutations
# ---------------------------------------------------------
type Mutation {
  # DONE: Create a new post
  createPost(input: CreatePostInput!):                          PostPayload

  # DONE: Update post
  updatePost(input: UpdatePostInput!):                          Boolean

  # FIXME: Delete a user post
  deletePost(input: DeletePostInput!):                          Boolean
}

# ---------------------------------------------------------
# *_: Subscriptions
# ---------------------------------------------------------
