# ---------------------------------------------------------
# Model Objects
# ---------------------------------------------------------
type Post {
  id:             ID!
  title:          String
  image:          File
  imagePublicId:  String
  authorId:       ID

  createdAt:      String
  updatedAt:      String
}

# ---------------------------------------------------------
# Input Objects
# ---------------------------------------------------------
input CreatePostInput {
  title:          String
  image:          Upload
  imagePublicId:  String
  private:        Boolean
}

input UpdatePostInput {
  id:             ID!
  title:          String
  private:        Boolean
}

input DeletePostInput {
  id:             ID!
  imagePublicId:  String
}

# ---------------------------------------------------------
# Return Payloads
# ---------------------------------------------------------
type PostPayload {
  id:             ID
  title:          String
  image:          String
  imagePublicId:  String
  authorId:       ID
  author:         UserPayload!
  private:        Boolean
  likes:         [UserPayload]
  comments:      [CommentPayload]

  createdAt:      String
  updatedAt:      String
}

type UserPostsPayload {
  posts:         [PostPayload]!
  count:          Int!
}

type PostsPayload {
  posts:         [PostPayload]!
  count:          Int!
}

# ---------------------------------------------------------
# Queries
# ---------------------------------------------------------
type Query {
  # Gets user posts by username
  getUserPosts(username: String!, skip: Int, limit: Int):       UserPostsPayload

  # Gets posts from authUser's followed users
  getFollowedPosts(skip: Int, limit: Int):                      PostsPayload

  # Gets post by id
  getPost(id: ID!):                                             PostPayload
}

# ---------------------------------------------------------
# Mutations
# ---------------------------------------------------------
type Mutation {
  # Creates a new post
  createPost(input: CreatePostInput!): PostPayload

  # Update post
  updatePost(input: UpdatePostInput!): PostPayload

  # Deletes a user post
  deletePost(input: DeletePostInput!): Boolean
}

# ---------------------------------------------------------
# Subscriptions
# ---------------------------------------------------------
