# ---------------------------------------------------------
# *_: Model Objects
# ---------------------------------------------------------

type StickerCollection {
  id:                       ID!
  thumbnailImage:           String!
  thumbnailImagePublicId:   String!
  name:                     String!
  description:              String
  authorId:                 ID!
  isPrivate:                Boolean!

  createdAt:                String!
  updatedAt:                String!
}

type Sticker {
  image:                    String!
  imagePublicId:            String!
  name:                     String!
  collectionId:             ID!

  createdAt:                String!
  updatedAt:                String!
}

# ---------------------------------------------------------
# *_: Input Objects
# ---------------------------------------------------------

input CreateStickerCollectionInput {
  thumbnailImage:           Upload!
  name:                     String!
  isPrivate:                Boolean!

  stickers:                [CreateStickerInput]
}

input CreateStickerInput {
  image:                    Upload!
  name:                     String!
}

input UpdateStickerInput {
  id:                       ID!
  name:                     String!
}

input UpdateStickerCollectionInput {
  id:                       ID!
  addStickers:             [Upload]
  deleteStickers:          [ID]
}

input DeleteStickerCollectionInput {
  id:                       ID!
}

# ---------------------------------------------------------
# *_: Return Payloads
# ---------------------------------------------------------

type StickerCollectionPayload {
  id:                       ID
  thumbnailImage:           String
  thumbnailImagePublicId:   String
  name:                     String
  description:              String
  authorId:                 ID
  isPrivate:                Boolean

  author:                   UserPayload
  stickers:                [StickerPayload]

  createdAt:                String
  updatedAt:                String
}

type StickerCollectionsPayload {
  count:                    Int
  stickerCollections:      [StickerCollectionPayload]
}

type StickerPayload {
  image:                    String
  imagePublicId:            String
  name:                     String
  collectionId:             ID

  createdAt:                String
  updatedAt:                String
}

# ---------------------------------------------------------
# *_: Queries
# ---------------------------------------------------------

type Query {
  # TODO:
  getStickerCollections(skip: Int, limit: Int):                         StickerCollectionsPayload   @deprecated(reason: "This's an upcoming api, not available at the moment.")

  # TODO:
  getInstalledStickerCollections(skip: Int, limit: Int):                StickerCollectionsPayload   @deprecated(reason: "This's an upcoming api, not available at the moment.")
}

# ---------------------------------------------------------
# *_: Mutations
# ---------------------------------------------------------

type Mutation {
  # TODO:
  createStickerCollection(input: CreateStickerCollectionInput!):          Boolean   @deprecated(reason: "This's an upcoming api, not available at the moment.")

  # TODO:
  updateStickerCollection(input: UpdateStickerCollectionInput!):          Boolean   @deprecated(reason: "This's an upcoming api, not available at the moment.")

  # TODO:
  deleteStickerCollection(input: DeleteStickerCollectionInput!):          Boolean   @deprecated(reason: "This's an upcoming api, not available at the moment.")
}

# ---------------------------------------------------------
# *_: Subscriptions
# ---------------------------------------------------------
