# ---------------------------------------------------------
# * Model Objects
# ---------------------------------------------------------

type User {
  id:                         ID!
  fullName:                   String!
  email:                      String!
  emailVerified:              Boolean!
  username:                   String!
  password:                   String!
  passwordResetToken:         String
  image:                      String
  imagePublicId:              String
  coverImage:                 String
  coverImagePublicId:         String
  visibleToEveryone:          Boolean!
  online:                     Boolean!
  displayOnlineStatus:        Boolean!
  lastActiveAt:               Float!

  createdAt:                  Float!
  updatedAt:                  Float!
}

# ---------------------------------------------------------
# * Input Objects
# ---------------------------------------------------------

input SignInInput {
  emailOrUsername:            String!
  password:                   String!
}

input SignUpInput {
  email:                      String!
  username:                   String!
  fullName:                   String!
  password:                   String!
  autoSignIn:                 Boolean!
}

input VerifyUserEmailInput {
  token:                      String!
}

input RequestPasswordResetInput {
  email:                      String
  username:                   String
}

input ResetPasswordInput {
  token:                      String!
  password:                   String!
}

input UpdateUserPasswordInput {
  password:                   String!
  newPassword:                String!
}

input UpdateUserInfoInput {
  email:                      String
  fullName:                   String
  visibleToEveryone:          Boolean
  displayOnlineStatus:        Boolean
}

input UpdateUserPhotoInput {
  image:                      Upload
  isCover:                    Boolean
}

# ---------------------------------------------------------
# * Response Payloads
# ---------------------------------------------------------

type AuthUserPayload {
  id:                         ID
  fullName:                   String
  email:                      String
  emailVerified:              Boolean       # Private, For authUser only
  username:                   String
  image:                      String
  imagePublicId:              String
  coverImage:                 String
  coverImagePublicId:         String
  visibleToEveryone:          Boolean       # Private, For authUser only
  online:                     Boolean
  displayOnlineStatus:        Boolean       # Private, For authUser only
  lastActiveAt:               Float

  createdAt:                  Float
  updatedAt:                  Float
}

type UserPayload {
  id:                         ID
  fullName:                   String
  email:                      String
  username:                   String
  image:                      String
  imagePublicId:              String
  coverImage:                 String
  coverImagePublicId:         String
  online:                     Boolean
  lastActiveAt:               Float

  createdAt:                  Float
}

type UsersPayload {
  count:                      Int
  users:                     [UserPayload]
}

type IsUserOnlinePayload {
  userId:                     ID
  online:                     Boolean
  lastActiveAt:               Float
}

type UpdateUserPhotoResponse {
  image:                      String
  imagePublicId:              String
  coverImage:                 String
  coverImagePublicId:         String
}

# ---------------------------------------------------------
# * Queries
# ---------------------------------------------------------

type Query {
  getAuthUser:                                                          AuthUserPayload @auth

  # Get user by username OR id
  getUser(username: String, id: ID):                                    UserPayload @auth(optional: true)

  # Get users except following and authUser
  getUsers(skip: Int, limit: Int):                                      UsersPayload @auth

  # Search users by username or fullName
  searchUsers(searchQuery: String!, skip: Int!, limit: Int!):           UsersPayload @auth

  suggestUsers(except: [ID]):                                          [UserPayload] @auth

  verifyToken(token: String!):                                          Boolean
}

# ---------------------------------------------------------
# * Mutations
# ---------------------------------------------------------

type Mutation {
  signup(input: SignUpInput!):                                          Boolean

  signin(input: SignInInput!):                                          Boolean

  signout:                                                              Boolean @auth

  requestVerificationEmail:                                             Boolean @auth

  verifyUserEmail(input: VerifyUserEmailInput!):                        Boolean

  requestPasswordReset(input: RequestPasswordResetInput!):              Boolean

  resetPassword(input: ResetPasswordInput!):                            Boolean

  updateUserPassword(input: UpdateUserPasswordInput!):                  Boolean @auth

  updateUserInfo(input: UpdateUserInfoInput!):                          AuthUserPayload @auth

  updateUserPhoto(input: UpdateUserPhotoInput!):                        UpdateUserPhotoResponse @auth
}

# ---------------------------------------------------------
# * Subscriptions
# ---------------------------------------------------------

type Subscription {
  isUserOnline(userId: ID!):                                            IsUserOnlinePayload
}
